server:
  port: 8001
spring:
  application:
    name: ad-sponsor
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ad?autoReconnect=true
    username: root
    password:
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/


